import { Router, Response } from 'express';
import { AuthenticatedRequest, authorize } from '../middleware/authorize';
import { prisma } from '../database';
import { ai } from '../utils/ai';
import Anthropic from '@anthropic-ai/sdk';

const router = Router();

// Initialize Anthropic
// Note: ANTHROPIC_API_KEY should be set in .env
const apiKey = process.env.ANTHROPIC_API_KEY;
const anthropic = apiKey ? new Anthropic({ apiKey }) : null;
const MODEL_NAME = "claude-3-haiku-20240307";

// Helper to get platform context
async function getPlatformContext() {
    try {
        const [investorCount, smeCount, advisorCount, dealCount] = await Promise.all([
            prisma.investor.count(),
            prisma.sME.count(),
            prisma.advisor.count(),
            prisma.deal.count()
        ]);

        // Fetch highlights
        const topInvestors = await prisma.investor.findMany({
            take: 3,
            select: { name: true, type: true }
        });
        const topSMEs = await prisma.sME.findMany({
            take: 3,
            select: { name: true, sector: true, stage: true }
        });
        const topAdvisors = await prisma.advisor.findMany({
            take: 3,
            select: { name: true, specialization: true }
        });

        // Safe context string
        return `
Platform Overview:
- Total Investors: ${investorCount}
- Total SMEs: ${smeCount}
- Total Advisors: ${advisorCount}
- Active Deals: ${dealCount}

Sample Investors: ${topInvestors.map(i => `${i.name} (${i.type})`).join(', ')}
Sample SMEs: ${topSMEs.map(s => `${s.name} (${s.sector} - ${s.stage})`).join(', ')}
Sample Advisors: ${topAdvisors.map(a => `${a.name} (${Array.isArray(a.specialization) ? a.specialization.join('/') : a.specialization})`).join(', ')}
        `;
    } catch (e) {
        console.error("Context fetch error:", e);
        return "Platform data currently limited.";
    }
}

// General Platform Chatbot
router.post('/chat', authorize('ai.chat'), async (req: AuthenticatedRequest, res: Response) => {
    try {
        const { message } = req.body;
        if (!message) return res.status(400).json({ error: "Message required" });

        if (!anthropic) {
            return res.json({
                response: "I am the AI Assistant (Claude). Please configure ANTHROPIC_API_KEY to enable real intelligence. I see you are asking about: " + message
            });
        }

        const context = await getPlatformContext();

        const systemPrompt = `
You are the AI Assistant for the Boutique Advisory Platform.
Your role is to help users (Investors, SMEs, Advisors) navigate the platform, understand the ecosystem, and find matches.
Context Data:
${context}
Instructions:
- Provide a helpful, professional answer based on the context.
- If asking about specific people not in the summary, encourage them to use the search feature.
- Be concise (max 3 sentences unless detailed info is requested).
        `;

        const msg = await anthropic.messages.create({
            model: MODEL_NAME,
            max_tokens: 1024,
            system: systemPrompt,
            messages: [
                { role: "user", content: message }
            ]
        });

        // Extract text response
        const textBlock = msg.content[0];
        const text = textBlock.type === 'text' ? textBlock.text : "No response text";

        return res.json({ response: text });
    } catch (error) {
        console.error("Claude Chat Error:", error);
        return res.status(500).json({ error: "AI Service Error: " + (error as any).message });
    }
});

// Generate AI summary for a deal
router.post('/analyze/:dealId', authorize('deal.read'), async (req: AuthenticatedRequest, res: Response) => {
    try {
        const { dealId } = req.params;

        const deal = await prisma.deal.findUnique({
            where: { id: dealId },
            include: { sme: true }
        });

        if (!deal) {
            return res.status(404).json({ error: 'Deal not found' });
        }

        // Use Claude if available
        if (anthropic) {
            const prompt = `Analyze this deal: ${deal.title} (${deal.sme.name}). Summary: ${deal.description || 'No description'}. Sector: ${deal.sme.sector}. Key risks and strengths?`;
            const msg = await anthropic.messages.create({
                model: MODEL_NAME,
                max_tokens: 1024,
                messages: [{ role: "user", content: prompt }]
            });
            const textBlock = msg.content[0];
            const text = textBlock.type === 'text' ? textBlock.text : "";
            return res.json({ summary: text, riskAnalysis: "AI Generated by Claude" });
        }

        const [summary, riskAnalysis] = await Promise.all([
            ai.generateDealSummary({ deal, sme: deal.sme }),
            ai.analyzeDealRisks({ deal, sme: deal.sme })
        ]);

        return res.json({ summary, riskAnalysis });
    } catch (error) {
        console.error('AI Analysis Route Error:', error);
        return res.status(500).json({ error: 'Internal server error' });
    }
});

// Chat with Dataroom AI
router.post('/chat/:dealId', authorize('deal.read'), async (req: AuthenticatedRequest, res: Response) => {
    try {
        const { dealId } = req.params;
        const { query } = req.body;

        const documents = await prisma.document.findMany({
            where: { dealId }
        });

        // Use Claude if available
        if (anthropic && documents.length > 0) {
            const docList = documents.map(d => d.name).join(', ');
            const prompt = `User asks about deal ${dealId}. Docs available: ${docList}. Query: ${query}. Answer based on this.`;
            const msg = await anthropic.messages.create({
                model: MODEL_NAME,
                max_tokens: 1024,
                messages: [{ role: "user", content: prompt }]
            });
            const textBlock = msg.content[0];
            return res.json({ answer: textBlock.type === 'text' ? textBlock.text : "" });
        }

        const answer = await ai.chatWithDataroom(query, documents);

        return res.json({ answer });
    } catch (error) {
        console.error('AI Chat Route Error:', error);
        return res.status(500).json({ error: 'Internal server error' });
    }
});

export default router;
